/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.50).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.asx.holdiay.HolidayCalender.api;
import com.asx.holdiay.HolidayCalender.model.Holiday;
import java.util.UUID;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-11-22T00:20:34.404919150Z[GMT]")
@Validated
public interface AustraliaHolidayApi {

    @Operation(summary = "Holidays based on Jurisdiction", description = "Holidays based on Jurisdiction.", tags={ "australia-holidays" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Holiday.class)))),
        
        @ApiResponse(responseCode = "400", description = "Invalid jurisdiction supplied"),
        
        @ApiResponse(responseCode = "404", description = "jurisdiction not found") })
    @RequestMapping(value = "/australia-holiday/state/{jurisdiction}/holidays",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Holiday>> getHolidaysByJurisdiction(@Parameter(in = ParameterIn.HEADER, description = "" ,required=true,schema=@Schema()) @RequestHeader(value="X-Request-ID", required=true) UUID xRequestID, @Parameter(in = ParameterIn.PATH, description = "jurisdiction", required=true, schema=@Schema()) @PathVariable("jurisdiction") String jurisdiction);

}

